export const data = [
  {
    id: 1,
    img: "../images/download.jpeg",
    img1: "../images/back1.jpeg",
    title: "Cropped Stay Groovy off white",
    prize: "$ 10.90",
    prize1: "1.21",
    installement: 9,
    quantity: 1,
    availableSize: "XL",
    isFreeShipping: true,
    styles: "White T-shirt",
  },
  {
    id: 2,
    img: "../images/images.jpeg",
    img1: "../images/back2.jpeg",
    title: "Basic Catcus White T-shirt",
    prize: "$ 13.25",
    prize1: "4.42",
    installement: 3,
    quantity: 1,
    availableSize: "XL",
    isFreeShipping: true,
    styles: "Wine",
  },
  {
    id: 3,
    img: "../images/download (2).jpeg",
    img1: "../images/back3.jpeg",
    title: "Skater Black Sweatshirt",
    prize: "$ 25.90",
    prize1: "2.16",
    installement: 12,
    quantity: 1,
    availableSize: "M",
    isFreeShipping: false,
    styles: "Tony Hawk",
  },
  {
    id: 4,
    img: "../images/download (6).jpeg",
    img1: "../images/back4.jpeg",
    title: "Black Tule Oversized",
    prize: "$ 29.45",
    prize1: "5.89",
    installement: 5,
    quantity: 1,
    availableSize: "ML",
    isFreeShipping: true,
    styles: "Tule",
  },
  {
    id: 5,
    img: "../images/download (5).jpeg",
    img1: "../images/back5.jpeg",
    title: "Black Batman T-shirt",
    prize: "$ 10.90",
    prize1: "1.21",
    installement: 9,
    quantity: 1,
    availableSize: "S",
    isFreeShipping: true,
    styles: "Really Cool T-shirt",
  },
  {
    id: 6,
    img: "../images/download 8.jpeg",
    img1: "../images/back6.jpeg",
    title: "Blue T-Shirt",
    prize: "$ 9.00",
    prize1: "3.00",
    installement: 3,
    quantity: 1,
    availableSize: "XXL",
    isFreeShipping: true,
    styles: "Mark Zuck have 365 of this one",
  },
  {
    id: 7,
    img: "../images/images (13).jpeg",
    img1: "../images/back7.jpeg",
    title: "Loose Black T-shirt",
    prize: "$ 14.00",
    prize1: "5.89",
    installement: 5,
    quantity: 1,
    isFreeShipping: true,
    availableSize: "XS",
  },
  {
    id: 8,
    img: "../images/download (9).jpeg",
    img1: "../images/back8.jpeg",
    title: "Ringer Hall Pass",
    prize: "$ 10.90",
    prize1: "1.21",
    installement: 9,
    quantity: 1,
    availableSize: "L",
    isFreeShipping: true,
    styles: "White T-shirt",
  },
  {
    id: 9,
    img: "../images/images (5).jpeg",
    img1: "../images/back9.jpeg",
    title: "Grey T-shirt",
    prize: "$ 14.90",
    prize1: "2.13",
    installement: 7,
    quantity: 1,
    availableSize: "S",
    isFreeShipping: true,
    styles: "You will like this one",
  },
  {
    id: 10,
    img: "../images/images (8).jpeg",
    img1: "../images/back10.jpeg",
    title: "Black T-shirt with white stripes",
    prize: "$ 14.90",
    prize1: "2.13",
    installement: 7,
    quantity: 1,
    availableSize: "S",
    isFreeShipping: true,
    styles: "Adidas originals",
  },
  {
    id: 11,
    img: "../images/download (10).jpeg",
    img1: "../images/back11.jpeg",
    title: "Turtles Ninja T-shirt",
    prize: "$ 10.90",
    prize1: "1.21",
    installement: 9,
    quantity: 1,
    availableSize: "M",
    isFreeShipping: false,
    styles: "Cowabunga!",
  },
  {
    id: 12,
    img: "../images/download (3).jpeg",
    img1: "../images/back12.jpeg",
    title: "Slim black T-shirt",
    prize: "$ 49.90",
    quantity: 1,
    availableSize: "XXL",
    isFreeShipping: true,
    styles: "Wenu you wish well",
  },
  {
    id: 13,
    img: "../images/images (10).jpeg",
    img1: "../images/back13.jpeg",
    title: "Blue Sweatshirt",
    prize: "$ 22.50",
    prize1: "5.63",
    installement: 4,
    quantity: 1,
    availableSize: "ML",
    isFreeShipping: true,
    styles: "Very comfy",
  },
  {
    id: 14,
    img: "../images/-473Wx593H-440749056-aqua-MODEL4.jpg",
    img1: "../images/back14.jpeg",
    title: "White T-shirt Gucci",
    prize: "$ 18.70",
    prize1: "4.67",
    installement: 4,
    quantity: 1,
    availableSize: "M",
    isFreeShipping: false,
    styles: "Girl the future is all your",
  },
  {
    id: 15,
    img: "../images/download (13).jpeg",
    img1: "../images/back15.jpeg",
    title: "Tropical Wine T-shirt",
    prize: "$ 134.90",
    prize1: "5.89",
    installement: 5,
    isFreeShipping: true,
    quantity: 1,
    availableSize: "XL",
  },
  {
    id: 16,
    img: "../images/download (11).jpeg",
    img1: "../images/back16.jpeg",
    title: "Marine Blue T-shirt",
    prize: "$ 49.00",
    prize1: "5.44",
    installement: 9,
    quantity: 1,
    isFreeShipping: true,
    availableSize: "S",
  },
];
